### Pandas Method Task

### Easy Level

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\lenovo\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")

In [4]:
1.
print(df.head(10))

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42
1          2    15647311      Hill          608     Spain  Female   41
2          3    15619304      Onio          502    France  Female   42
3          4    15701354      Boni          699    France  Female   39
4          5    15737888  Mitchell          850     Spain  Female   43
5          6    15574012       Chu          645     Spain    Male   44
6          7    15592531  Bartlett          822    France    Male   50
7          8    15656148    Obinna          376   Germany  Female   29
8          9    15792365        He          501    France    Male   44
9         10    15592389        H?          684    France    Male   27

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1
5       8  113755.78              2          1               0
6       7       0.00              2          1               1
7       4  115046.74              4          1               0
8       4  142051.07              2          0               1
9       2  134603.88              1          1               1

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0
5        149756.71       1
6         10062.80       0
7        119346.88       1
8         74940.50       0
9         71725.73       0

In [13]:
2.
df.tail(15)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [14]:
3.
df.sample(7)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
504,505,15715527,Freeman,543,Spain,Female,41,4,0.00,1,0,0,194902.16,0
2755,2756,15625522,Walker,700,Spain,Male,31,7,0.00,2,0,1,145151.96,0
8657,8658,15684316,Udokamma,532,France,Male,43,9,0.00,2,0,0,190573.91,1
3059,3060,15670619,Coppin,631,France,Female,33,8,0.00,2,0,0,117374.22,0
3782,3783,15680449,Hsing,431,Germany,Female,44,2,138843.70,1,1,0,37688.31,1
6850,6851,15579526,O'Meara,551,France,Male,42,1,50194.59,1,1,1,23399.58,0
1477,1478,15732175,Bruno,776,France,Male,37,2,0.00,1,0,1,8065.00,0

In [15]:
4.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [16]:
5.
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
6.
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [24]:
7.
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [31]:
8.
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [34]:
9.
df.drop_duplicates()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [39]:
10.
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

### Medium Level

In [7]:
11.
df.rename(columns={"Coustomerld" : "Customer_ID","CreditScore" : "Credit_Score","EstimatedSalary" : "Salary","Exited" : "Churn"})
df.rename

<bound method DataFrame.rename of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42
1             2    15647311       Hill          608     Spain  Female   41
2             3    15619304       Onio          502    France  Female   42
3             4    15701354       Boni          699    France  Female   39
4             5    15737888   Mitchell          850     Spain  Female   43
...         ...         ...        ...          ...       ...     ...  ...
9995       9996    15606229   Obijiaku          771    France    Male   39
9996       9997    15569892  Johnstone          516    France    Male   35
9997       9998    15584532        Liu          709    France  Female   36
9998       9999    15682355  Sabbatini          772   Germany    Male   42
9999      10000    15628319     Walker          792    France  Female   28

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1
1          1   83807.86              1          0               1
2          8  159660.80              3          1               0
3          1       0.00              2          0               0
4          2  125510.82              1          1               1
...      ...        ...            ...        ...             ...
9995       5       0.00              2          1               0
9996      10   57369.61              1          1               1
9997       7       0.00              1          0               1
9998       3   75075.31              2          1               0
9999       4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 14 columns]>

In [44]:
12.
df.add_prefix("Bank_")

,Bank_RowNumber,Bank_CustomerId,Bank_Surname,Bank_CreditScore,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_EstimatedSalary,Bank_Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [15]:
13.
df["Age"] = df["Age"].astype(float)

In [12]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
14.
df['Bank_Churn'] = df[Bank_Churn'].astype("string")

In [18]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [28]:
15.
Balance_mean = df["Balance"].mean()

df["Balance"] = df["Balance"].fillna(Balance_mean)
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [31]:
16.
print(df["Age"].isnull().sum())

0

In [52]:
17.
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [53]:
18.
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [49]:
19.
df.drop("Geography", axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Gender           10000 non-null  object
 5   Age              10000 non-null  int64
 6   Tenure           10000 non-null  int64
 7   Balance          10000 non-null  float64
 8   NumOfProducts    10000 non-null  int64
 9   HasCrCard        10000 non-null  int64
 10  IsActiveMember   10000 non-null  int64
 11  EstimatedSalary  10000 non-null  float64
 12  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(2)
memory usage: 1015.8+ KB

In [51]:
20.
df.rename(columns={"Bank_NumOfProducts":"Products","Bank_HasCrCard":"CreditCard"},inplace = True)
df.rename

<bound method DataFrame.rename of       RowNumber  CustomerId    Surname  CreditScore  Gender  Age  Tenure  \
0             1    15634602   Hargrave          619  Female   42       2
1             2    15647311       Hill          608  Female   41       1
2             3    15619304       Onio          502  Female   42       8
3             4    15701354       Boni          699  Female   39       1
4             5    15737888   Mitchell          850  Female   43       2
...         ...         ...        ...          ...     ...  ...     ...
9995       9996    15606229   Obijiaku          771    Male   39       5
9996       9997    15569892  Johnstone          516    Male   35      10
9997       9998    15584532        Liu          709  Female   36       7
9998       9999    15682355  Sabbatini          772    Male   42       3
9999      10000    15628319     Walker          792  Female   28       4

        Balance  Products  CreditCard  IsActiveMember  EstimatedSalary  Exited
0          0.00         1           1               1        101348.88       1
1      83807.86         1           0               1        112542.58       0
2     159660.80         3           1               0        113931.57       1
3          0.00         2           0               0         93826.63       0
4     125510.82         1           1               1         79084.10       0
...         ...       ...         ...             ...              ...     ...
9995       0.00         2           1               0         96270.64       0
9996   57369.61         1           1               1        101699.77       0
9997       0.00         1           0               1         42085.58       1
9998   75075.31         2           1               0         92888.52       1
9999  130142.79         1           1               0         38190.78       0

[10000 rows x 13 columns]>

### Hard Level

In [58]:
21.
df.rename(columns = {
    "RowNumber" : "Row_No",
    "Customerid" : "Customer_ID",
    "Surname" : "Last_Name",
    "CreditScore" : "Credit_Score",
    "Geography" : "Country",
    "Gender" : "Sex",
    "EstimatedSalary" : "Salary",
    "Exited" : "Target",
})
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
22.

In [52]:
23.
df.duplicated().sum()

np.int64(0)

In [53]:
df.drop_duplicates()

,RowNumber,CustomerId,Surname,CreditScore,Gender,Age,Tenure,Balance,Products,CreditCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28,4,130142.79,1,1,0,38190.78,0

In [54]:
24.
df.add_prefix('customer_')

,customer_RowNumber,customer_CustomerId,customer_Surname,customer_CreditScore,customer_Gender,customer_Age,customer_Tenure,customer_Balance,customer_Products,customer_CreditCard,customer_IsActiveMember,customer_EstimatedSalary,customer_Exited
0,1,15634602,Hargrave,619,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
25.
df["Age"]= df["Age"].astype(float)
df["Balance"]= df["Balance"].astype(float)
df["Salary"]= df["Salary"].astype(float)

df.info()

KeyError: 'Salary'

In [6]:
26.
df["CreditScore"] = df["Credit_Score"].fillna(df["Credit_Score"].median())
print(df["CreditScore"].isnull.sum())

KeyError: 'Credit_Score'

In [7]:
27.
df["EstimatedSalary"] = df["EstimatedSalary"].fillna(
    df["EstimatedSalary"].mean()
)
print(df.head(8))

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave          619    France  Female  42.0
1          2    15647311      Hill          608     Spain  Female  41.0
2          3    15619304      Onio          502    France  Female  42.0
3          4    15701354      Boni          699    France  Female  39.0
4          5    15737888  Mitchell          850     Spain  Female  43.0
5          6    15574012       Chu          645     Spain    Male  44.0
6          7    15592531  Bartlett          822    France    Male  50.0
7          8    15656148    Obinna          376   Germany  Female  29.0

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1
1       1   83807.86              1          0               1
2       8  159660.80              3          1               0
3       1       0.00              2          0               0
4       2  125510.82              1          1               1
5       8  113755.78              2          1               0
6       7       0.00              2          1               1
7       4  115046.74              4          1               0

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0
5        149756.71       1
6         10062.80       0
7        119346.88       1

In [8]:
28.
df = df.drop_duplicates()
df = df.rename(columns={"Exited": "Target"})

df["Target"] = df["Target"].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Target           10000 non-null  object
dtypes: float64(3), int64(7), object(4)
memory usage: 1.1+ MB

In [9]:
29.
df_copy = df.copy()

df_copy = df_copy.rename(columns={
    "Gender": "CustomerGender",
    "Geography": "Country"
})

df_copy = df_copy.add_prefix("Bank_")

df_copy = df_copy.drop(columns=["Bank_RowNumber"])

print(df_copy.head(10))

   Bank_CustomerId Bank_Surname  Bank_CreditScore Bank_Country  \
0         15634602     Hargrave               619       France
1         15647311         Hill               608        Spain
2         15619304         Onio               502       France
3         15701354         Boni               699       France
4         15737888     Mitchell               850        Spain
5         15574012          Chu               645        Spain
6         15592531     Bartlett               822       France
7         15656148       Obinna               376      Germany
8         15792365           He               501       France
9         15592389           H?               684       France

  Bank_CustomerGender  Bank_Age  Bank_Tenure  Bank_Balance  \
0              Female      42.0            2          0.00
1              Female      41.0            1      83807.86
2              Female      42.0            8     159660.80
3              Female      39.0            1          0.00
4              Female      43.0            2     125510.82
5                Male      44.0            8     113755.78
6                Male      50.0            7          0.00
7              Female      29.0            4     115046.74
8                Male      44.0            4     142051.07
9                Male      27.0            2     134603.88

   Bank_NumOfProducts  Bank_HasCrCard  Bank_IsActiveMember  \
0                   1               1                    1
1                   1               0                    1
2                   3               1                    0
3                   2               0                    0
4                   1               1                    1
5                   2               1                    0
6                   2               1                    1
7                   4               1                    0
8                   2               0                    1
9                   1               1                    1

   Bank_EstimatedSalary Bank_Target
0             101348.88           1
1             112542.58           0
2             113931.57           1
3              93826.63           0
4              79084.10           0
5             149756.71           1
6              10062.80           0
7             119346.88           1
8              74940.50           0
9              71725.73           0

In [13]:
30.
# 1. Load the dataset
df = pd.read_csv("C:\\Users\\lenovo\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")

# 2. Display dataset information
df.info()

# 3. Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# 4. Remove duplicate rows
df = df.drop_duplicates()

# 5. Rename columns
df = df.rename(columns={
    "CustomerId": "Customer_ID",
    "CreditScore": "Credit_Score",
    "EstimatedSalary": "Salary",
    "Exited": "Target"
})

# 6. Convert data types
df["Age"] = df["Age"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

# 7. Replace missing values
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

# 8. Remove RowNumber and Surname
df = df.drop(columns=["RowNumber", "Surname"])

# 9a. Display first 10 rows
print("\nFirst 10 Rows:")
print(df.head(10))

# 9b. Display statistical summary
print("\nStatistical Summary:")
print(df.describe())

# 9c. Display value counts of Target
print("\nTarget Value Counts:")
print(df["Target"].value_counts())

# 9d. Display final dataset information
print("\nFinal Dataset Information:")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

Missing Values:
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

First 10 Rows:
   Customer_ID  Credit_Score Geography  Gender   Age  Tenure    Balance  \
0     15634602           619    France  Female  42.0       2       0.00
1     15647311           608     Spain  Female  41.0       1   83807.86
2     15619304           502    France  Female  42.0       8  159660.80
3     15701354           699    France  Female  39.0       1       0.00
4     15737888           850     Spain  Female  43.0       2  125510.82
5     15574012           645     Spain    Male  44.0       8  113755.78
6     15592531           822    France    Male  50.0       7       0.00
7     15656148           376   Germany  Female  29.0       4  115046.74
8     15792365           501    France    Male  44.0       4  142051.07
9     15592389           684    France    Male  27.0       2  134603.88

   NumOfProducts  HasCrCard  IsActiveMember     Salary Target
0              1          1               1  101348.88      1
1              1          0               1  112542.58      0
2              3          1               0  113931.57      1
3              2          0               0   93826.63      0
4              1          1               1   79084.10      0
5              2          1               0  149756.71      1
6              2          1               1   10062.80      0
7              4          1               0  119346.88      1
8              2          0               1   74940.50      0
9              1          1               1   71725.73      0

Statistical Summary:
        Customer_ID  Credit_Score           Age        Tenure        Balance  \
count  1.000000e+04  10000.000000  10000.000000  10000.000000   10000.000000
mean   1.569094e+07    650.528800     38.921800      5.012800   76485.889288
std    7.193619e+04     96.653299     10.487806      2.892174   62397.405202
min    1.556570e+07    350.000000     18.000000      0.000000       0.000000
25%    1.562853e+07    584.000000     32.000000      3.000000       0.000000
50%    1.569074e+07    652.000000     37.000000      5.000000   97198.540000
75%    1.575323e+07    718.000000     44.000000      7.000000  127644.240000
max    1.581569e+07    850.000000     92.000000     10.000000  250898.090000

       NumOfProducts    HasCrCard  IsActiveMember         Salary
count   10000.000000  10000.00000    10000.000000   10000.000000
mean        1.530200      0.70550        0.515100  100090.239881
std         0.581654      0.45584        0.499797   57510.492818
min         1.000000      0.00000        0.000000      11.580000
25%         1.000000      0.00000        0.000000   51002.110000
50%         1.000000      1.00000        1.000000  100193.915000
75%         2.000000      1.00000        1.000000  149388.247500
max         4.000000      1.00000        1.000000  199992.480000

Target Value Counts:
Target
0    7963
1    2037
Name: count, dtype: int64

Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     10000 non-null  int64
 1   Credit_Score    10000 non-null  int64
 2   Geography       10000 non-null  object
 3   Gender          10000 non-null  object
 4   Age             10000 non-null  float64
 5   Tenure          10000 non-null  int64
 6   Balance         10000 non-null  float64
 7   NumOfProducts   10000 non-null  int64
 8   HasCrCard       10000 non-null  int64
 9   IsActiveMember  10000 non-null  int64
 10  Salary          10000 non-null  float64
 11  Target          10000 non-null  object
dtypes: float64(3), int64(6), object(3)
memory usage: 937.6+ KB

### Bonus Challenge (Create New Columns)

In [14]:
# B1
df["TotalMoney"] = df["Balance"] + df["Salary"]
df.head()

,Customer_ID,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,TotalMoney
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,101348.88
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,196350.44
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,273592.37
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,93826.63
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,204594.92

In [16]:
# B2
df["DoubleScore"] = df["Credit_Score"] * 2
df.head()

,Customer_ID,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,TotalMoney,DoubleScore
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,101348.88,1238
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,196350.44,1216
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,273592.37,1004
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,93826.63,1398
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,204594.92,1700

In [17]:
# B3
df["AgeAfter10Years"] = df["Age"] + 10
df.head()

,Customer_ID,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,TotalMoney,DoubleScore,AgeAfter10Years
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,101348.88,1238,52.0
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,196350.44,1216,51.0
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,273592.37,1004,52.0
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,93826.63,1398,49.0
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,204594.92,1700,53.0

In [18]:
# B4
df["HasBalance"] = df["Balance"]

df["HasBalance"] = df["HasBalance"].fillna(df["HasBalance"].mean())
df.head()

,Customer_ID,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,TotalMoney,DoubleScore,AgeAfter10Years,HasBalance
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,101348.88,1238,52.0,0.00
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,196350.44,1216,51.0,83807.86
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,273592.37,1004,52.0,159660.80
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,93826.63,1398,49.0,0.00
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,204594.92,1700,53.0,125510.82

In [19]:
# B5
df["SalaryInLakhs"] = df["Salary"] / 100000
df.head()

,Customer_ID,Credit_Score,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Salary,Target,TotalMoney,DoubleScore,AgeAfter10Years,HasBalance,SalaryInLakhs
0,15634602,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1,101348.88,1238,52.0,0.00,1.013489
1,15647311,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,196350.44,1216,51.0,83807.86,1.125426
2,15619304,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,273592.37,1004,52.0,159660.80,1.139316
3,15701354,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,93826.63,1398,49.0,0.00,0.938266
4,15737888,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,204594.92,1700,53.0,125510.82,0.790841