### Flight Price Datasets

In [4]:
import pandas as pd

In [5]:
import numpy as np

In [7]:
1.
df = pd.read_csv("C:\\Users\\lenovo\\Downloads\\Data_Train.xlsx - Sheet1.csv")
df.head(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [8]:
2.
df.shape

(10683, 11)

In [9]:
3.
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [11]:
4.
df.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

In [12]:
5.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [13]:
6.
df.dropna()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [14]:
7.
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

Airline            0.000000
Date_of_Journey    0.000000
Source             0.000000
Destination        0.000000
Route              0.009361
Dep_Time           0.000000
Arrival_Time       0.000000
Duration           0.000000
Total_Stops        0.009361
Additional_Info    0.000000
Price              0.000000
dtype: float64

In [15]:
8.
df['Airline'].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [16]:
9.
df['Total_Stops'].value_counts(dropna=True)

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [18]:
10.
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"],dayfirst=True)

df["Date_of_Journey"].head()

0   2019-03-24
1   2019-05-01
2   2019-06-09
3   2019-05-12
4   2019-03-01
Name: Date_of_Journey, dtype: datetime64[ns]

In [19]:
11.
df['Day'] = df['Date_of_Journey'].dt.day
df['Day']

0        24
1         1
2         9
3        12
4         1
         ..
10678     9
10679    27
10680    27
10681     1
10682     9
Name: Day, Length: 10683, dtype: int32

In [20]:
12.
df['Month'] = df['Date_of_Journey'].dt.month
df['Month']

0        3
1        5
2        6
3        5
4        3
        ..
10678    4
10679    4
10680    4
10681    3
10682    5
Name: Month, Length: 10683, dtype: int32

In [21]:
13.
df['Year'] = df['Date_of_Journey'].dt.year
df['Year']

0        2019
1        2019
2        2019
3        2019
4        2019
         ...
10678    2019
10679    2019
10680    2019
10681    2019
10682    2019
Name: Year, Length: 10683, dtype: int32

In [ ]:
14.
df.drop('Date_of_Journey', axis=1, inplace=True)
df.head()

In [25]:
15.
df['Dep_Time'] = pd.to_datetime(df['Dep_Time'],format='%H:%M',)
df['Dep_Hour'] = df['Dep_Time'].dt.hour
df['Dep_Hour']

0        22
1         5
2         9
3        18
4        16
         ..
10678    19
10679    20
10680     8
10681    11
10682    10
Name: Dep_Hour, Length: 10683, dtype: int32

In [26]:
16.
df['Dep_Minute'] = df['Dep_Time'].dt.minute
df['Dep_Minute']

0        20
1        50
2        25
3         5
4        50
         ..
10678    55
10679    45
10680    20
10681    30
10682    55
Name: Dep_Minute, Length: 10683, dtype: int32

In [ ]:
17.
df.drop('Dep_Time', axis=1, inplace=True)

In [27]:
18.
df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'],format='mixed',errors='coerce')

df['Arrival_Time'] = df['Arrival_Time'].dt.time

In [ ]:
19.
df["Arrival_Hour"] = pd.to_datetime(
    df["Arrival_Time"].astype(str),
    errors="coerce"
).dt.hour

df["Arrival_Minute"] = pd.to_datetime(
    df["Arrival_Time"].astype(str),
    errors="coerce"
).dt.minute

print(df[["Arrival_Hour", "Arrival_Minute"]].head())

In [ ]:
20.
df.drop('Arrival_Time', axis=1, inplace=True)

In [28]:
21.
df['Duration_Hour'] = (
    df["Duration"]
    .str.extract(r'(\d+)\s*h',expand=False)
    .fillna(0)
    .astype(int)
)

df['Duration_Hour']

0         2
1         7
2        19
3         5
4         4
         ..
10678     2
10679     2
10680     3
10681     2
10682     8
Name: Duration_Hour, Length: 10683, dtype: int64

In [29]:
22.
df['Duration_Minute'] = (
    df['Duration']
    .str.extract(r'(\d+)\s*m',expand=False)
    .fillna(0)
    .astype(int)
)

df['Duration_Minute']

0        50
1        25
2         0
3        25
4        45
         ..
10678    30
10679    35
10680     0
10681    40
10682    20
Name: Duration_Minute, Length: 10683, dtype: int64

In [ ]:
23.
df.drop('Duration', axis=1, inplace=True)

In [30]:
24.
df['Total_Stops'] = df['Total_Stops'].replace("non-stop", 0)
df['Total_Stops']

0              0
1        2 stops
2        2 stops
3         1 stop
4         1 stop
          ...
10678          0
10679          0
10680          0
10681          0
10682    2 stops
Name: Total_Stops, Length: 10683, dtype: object

In [ ]:
25.
df["Total_Stops"] = pd.to_numeric(
    df["Total_Stops"].astype(str).str.extract(r"(\d+)")[0],
    errors="coerce"
)

df["Total_Stops"] = df["Total_Stops"].fillna(0)

df["Total_Stops"] = df["Total_Stops"].astype(int)

print(df["Total_Stops"].unique())

In [ ]:
26.
# Split Route using → as the separator
route_columns = df["Route"].str.split("→", expand=True)

# Create Route_1 to Route_5
for i in range(5):
    df[f"Route_{i+1}"] = route_columns[i]

print(df[["Route_1", "Route_2", "Route_3", "Route_4", "Route_5"]].head())

In [ ]:
27.
df[['Route_3', 'Route_4', 'Route_5']].isnull().sum()

In [ ]:
28.
route_cols = [
    "Route_1",
    "Route_2",
    "Route_3",
    "Route_4",
    "Route_5"
]

df[route_cols] = df[route_cols].fillna("None")

print(df[route_cols].head())

In [ ]:
29.
29.
df.drop('Route_5',axis = 1)

In [34]:
30.
X = df.drop('Price', axis=1)
y = df['Price']

In [35]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Arrival_Time',
       'Duration', 'Total_Stops', 'Additional_Info', 'Price', 'Day', 'Month',
       'Year', 'Dep_Hour', 'Dep_Minute', 'Duration_Hour', 'Duration_Minute'],
      dtype='object')